# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RPIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slideMenuContainer = QtWidgets.QFrame(self.centralwidget)
        self.slideMenuContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.slideMenuContainer.setMaximumSize(QtCore.QSize(0, 16777215))
        self.slideMenuContainer.setStyleSheet("")
        self.slideMenuContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slideMenuContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slideMenuContainer.setObjectName("slideMenuContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slideMenuContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slideMenu = QtWidgets.QFrame(self.slideMenuContainer)
        self.slideMenu.setMinimumSize(QtCore.QSize(400, 0))
        self.slideMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.slideMenu.setStyleSheet("")
        self.slideMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slideMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slideMenu.setObjectName("slideMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.slideMenu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sideMenuLabelFrame = QtWidgets.QFrame(self.slideMenu)
        self.sideMenuLabelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideMenuLabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideMenuLabelFrame.setObjectName("sideMenuLabelFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.sideMenuLabelFrame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sideMenuLabel = QtWidgets.QLabel(self.sideMenuLabelFrame)
        self.sideMenuLabel.setStyleSheet("")
        self.sideMenuLabel.setObjectName("sideMenuLabel")
        self.horizontalLayout_10.addWidget(self.sideMenuLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sideMenuDuck = QtWidgets.QPushButton(self.sideMenuLabelFrame)
        self.sideMenuDuck.setStyleSheet("border-style: flat;")
        self.sideMenuDuck.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/duck.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideMenuDuck.setIcon(icon)
        self.sideMenuDuck.setIconSize(QtCore.QSize(50, 50))
        self.sideMenuDuck.setObjectName("sideMenuDuck")
        self.horizontalLayout_10.addWidget(self.sideMenuDuck, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.sideMenuLabelFrame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dropMenuFrame = QtWidgets.QFrame(self.slideMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropMenuFrame.sizePolicy().hasHeightForWidth())
        self.dropMenuFrame.setSizePolicy(sizePolicy)
        self.dropMenuFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.dropMenuFrame.setStyleSheet("")
        self.dropMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropMenuFrame.setObjectName("dropMenuFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dropMenuFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dropMenu = QtWidgets.QToolBox(self.dropMenuFrame)
        self.dropMenu.setStyleSheet("")
        self.dropMenu.setObjectName("dropMenu")
        self.toolsPage = QtWidgets.QWidget()
        self.toolsPage.setGeometry(QtCore.QRect(0, 0, 372, 596))
        self.toolsPage.setStyleSheet("")
        self.toolsPage.setObjectName("toolsPage")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.toolsPage)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.toolPageFrame = QtWidgets.QFrame(self.toolsPage)
        self.toolPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolPageFrame.setObjectName("toolPageFrame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.toolPageFrame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.imageToVideo = QtWidgets.QPushButton(self.toolPageFrame)
        self.imageToVideo.setStyleSheet("")
        self.imageToVideo.setObjectName("imageToVideo")
        self.verticalLayout_22.addWidget(self.imageToVideo, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_21.addWidget(self.toolPageFrame, 0, QtCore.Qt.AlignTop)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dropMenu.addItem(self.toolsPage, icon1, "")
        self.systemInformationPage = QtWidgets.QWidget()
        self.systemInformationPage.setGeometry(QtCore.QRect(0, 0, 372, 596))
        self.systemInformationPage.setObjectName("systemInformationPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.systemInformationPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.systemInformationFrame = QtWidgets.QFrame(self.systemInformationPage)
        self.systemInformationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.systemInformationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.systemInformationFrame.setObjectName("systemInformationFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.systemInformationFrame)
        self.verticalLayout_10.setContentsMargins(0, 7, 0, 6)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.overall = QtWidgets.QPushButton(self.systemInformationFrame)
        self.overall.setStyleSheet("")
        self.overall.setObjectName("overall")
        self.verticalLayout_10.addWidget(self.overall)
        self.verticalLayout_7.addWidget(self.systemInformationFrame)
        self.dropMenu.addItem(self.systemInformationPage, icon1, "")
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setGeometry(QtCore.QRect(0, 0, 372, 596))
        self.settingsPage.setObjectName("settingsPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.settingsPage)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.settingsPageFrame = QtWidgets.QFrame(self.settingsPage)
        self.settingsPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsPageFrame.setObjectName("settingsPageFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.settingsPageFrame)
        self.verticalLayout_11.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.versionInformation = QtWidgets.QPushButton(self.settingsPageFrame)
        self.versionInformation.setStyleSheet("")
        self.versionInformation.setObjectName("versionInformation")
        self.verticalLayout_11.addWidget(self.versionInformation)
        self.preferences = QtWidgets.QPushButton(self.settingsPageFrame)
        self.preferences.setStyleSheet("")
        self.preferences.setObjectName("preferences")
        self.verticalLayout_11.addWidget(self.preferences)
        self.verticalLayout_8.addWidget(self.settingsPageFrame, 0, QtCore.Qt.AlignTop)
        self.dropMenu.addItem(self.settingsPage, icon1, "")
        self.verticalLayout_4.addWidget(self.dropMenu)
        self.verticalLayout_3.addWidget(self.dropMenuFrame)
        self.exitFrame = QtWidgets.QFrame(self.slideMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitFrame.sizePolicy().hasHeightForWidth())
        self.exitFrame.setSizePolicy(sizePolicy)
        self.exitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exitFrame.setObjectName("exitFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.exitFrame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.exitButton = QtWidgets.QPushButton(self.exitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setStyleSheet("color: rgb(230, 230, 230);\n"
"font: 14pt \"Century Gothic\";\n"
"border-style: flat;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(40, 40))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_11.addWidget(self.exitButton)
        self.verticalLayout_3.addWidget(self.exitFrame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.slideMenu)
        self.horizontalLayout.addWidget(self.slideMenuContainer)
        self.mainBody = QtWidgets.QFrame(self.centralwidget)
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerframe = QtWidgets.QFrame(self.mainBody)
        self.headerframe.setStyleSheet("")
        self.headerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerframe.setObjectName("headerframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerframe)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.headerMenuFrame = QtWidgets.QFrame(self.headerframe)
        self.headerMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerMenuFrame.setObjectName("headerMenuFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.headerMenuFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.headerMenuButton = QtWidgets.QPushButton(self.headerMenuFrame)
        self.headerMenuButton.setStyleSheet("border-style: flat;")
        self.headerMenuButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.headerMenuButton.setIcon(icon3)
        self.headerMenuButton.setIconSize(QtCore.QSize(50, 50))
        self.headerMenuButton.setObjectName("headerMenuButton")
        self.horizontalLayout_9.addWidget(self.headerMenuButton)
        self.horizontalLayout_2.addWidget(self.headerMenuFrame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.headerHomeFrame = QtWidgets.QFrame(self.headerframe)
        self.headerHomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerHomeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerHomeFrame.setObjectName("headerHomeFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.headerHomeFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.headerHomeButton = QtWidgets.QPushButton(self.headerHomeFrame)
        self.headerHomeButton.setStyleSheet("border-style: flat;")
        self.headerHomeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.headerHomeButton.setIcon(icon4)
        self.headerHomeButton.setIconSize(QtCore.QSize(50, 50))
        self.headerHomeButton.setObjectName("headerHomeButton")
        self.horizontalLayout_8.addWidget(self.headerHomeButton)
        self.horizontalLayout_2.addWidget(self.headerHomeFrame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.headerVemiFrame = QtWidgets.QFrame(self.headerframe)
        self.headerVemiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerVemiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerVemiFrame.setObjectName("headerVemiFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerVemiFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.headerVemiButton = QtWidgets.QPushButton(self.headerVemiFrame)
        self.headerVemiButton.setStyleSheet("border-style: flat;")
        self.headerVemiButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/VEMI_Logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.headerVemiButton.setIcon(icon5)
        self.headerVemiButton.setIconSize(QtCore.QSize(100, 50))
        self.headerVemiButton.setObjectName("headerVemiButton")
        self.horizontalLayout_5.addWidget(self.headerVemiButton)
        self.horizontalLayout_2.addWidget(self.headerVemiFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.headerControlFrame = QtWidgets.QFrame(self.headerframe)
        self.headerControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerControlFrame.setObjectName("headerControlFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerControlFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimize = QtWidgets.QPushButton(self.headerControlFrame)
        self.minimize.setStyleSheet("border-style: flat;")
        self.minimize.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize.setIcon(icon6)
        self.minimize.setIconSize(QtCore.QSize(50, 50))
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_4.addWidget(self.minimize)
        self.fullScreen = QtWidgets.QPushButton(self.headerControlFrame)
        self.fullScreen.setStyleSheet("border-style: flat;\n"
"")
        self.fullScreen.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fullScreen.setIcon(icon7)
        self.fullScreen.setIconSize(QtCore.QSize(45, 45))
        self.fullScreen.setObjectName("fullScreen")
        self.horizontalLayout_4.addWidget(self.fullScreen)
        self.exit = QtWidgets.QPushButton(self.headerControlFrame)
        self.exit.setStyleSheet("border-style: flat;")
        self.exit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon8)
        self.exit.setIconSize(QtCore.QSize(50, 50))
        self.exit.setObjectName("exit")
        self.horizontalLayout_4.addWidget(self.exit)
        self.horizontalLayout_2.addWidget(self.headerControlFrame, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.headerframe)
        self.mainBodyContents = QtWidgets.QFrame(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContents.sizePolicy().hasHeightForWidth())
        self.mainBodyContents.setSizePolicy(sizePolicy)
        self.mainBodyContents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBodyContents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBodyContents.setObjectName("mainBodyContents")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.mainBodyContents)
        self.horizontalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainBodyContents)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.homePage)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_14 = QtWidgets.QLabel(self.homePage)
        self.label_14.setStyleSheet("font: 24pt \"Century Gothic\";\n"
"color: rgb(230, 230, 230);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_27.addWidget(self.label_14)
        self.stackedWidget.addWidget(self.homePage)
        self.imageToVid = QtWidgets.QWidget()
        self.imageToVid.setObjectName("imageToVid")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.imageToVid)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.imageToVidLabelFrame = QtWidgets.QFrame(self.imageToVid)
        self.imageToVidLabelFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.imageToVidLabelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageToVidLabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageToVidLabelFrame.setObjectName("imageToVidLabelFrame")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.imageToVidLabelFrame)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame = QtWidgets.QFrame(self.imageToVidLabelFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.imageToVidTitle = QtWidgets.QLabel(self.frame_3)
        self.imageToVidTitle.setMaximumSize(QtCore.QSize(800, 16777215))
        self.imageToVidTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.imageToVidTitle.setObjectName("imageToVidTitle")
        self.horizontalLayout_30.addWidget(self.imageToVidTitle)
        self.verticalLayout_23.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_24.addWidget(self.tableWidget)
        self.verticalLayout_23.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem)
        self.imageToVidUploadFile = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageToVidUploadFile.sizePolicy().hasHeightForWidth())
        self.imageToVidUploadFile.setSizePolicy(sizePolicy)
        self.imageToVidUploadFile.setMinimumSize(QtCore.QSize(250, 0))
        self.imageToVidUploadFile.setMaximumSize(QtCore.QSize(250, 16777215))
        self.imageToVidUploadFile.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageToVidUploadFile.setIcon(icon9)
        self.imageToVidUploadFile.setObjectName("imageToVidUploadFile")
        self.horizontalLayout_31.addWidget(self.imageToVidUploadFile)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem1)
        self.imageToVidUploadFolder = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageToVidUploadFolder.sizePolicy().hasHeightForWidth())
        self.imageToVidUploadFolder.setSizePolicy(sizePolicy)
        self.imageToVidUploadFolder.setMinimumSize(QtCore.QSize(250, 0))
        self.imageToVidUploadFolder.setMaximumSize(QtCore.QSize(150, 16777215))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageToVidUploadFolder.setIcon(icon10)
        self.imageToVidUploadFolder.setObjectName("imageToVidUploadFolder")
        self.horizontalLayout_31.addWidget(self.imageToVidUploadFolder)
        spacerItem2 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem2)
        self.verticalLayout_23.addWidget(self.frame_5)
        self.horizontalLayout_29.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.imageToVidLabelFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_34.addWidget(self.label_15)
        self.verticalLayout_33.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.imageToVidConvert = QtWidgets.QPushButton(self.frame_7)
        self.imageToVidConvert.setMinimumSize(QtCore.QSize(250, 0))
        self.imageToVidConvert.setMaximumSize(QtCore.QSize(300, 16777215))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/corner-down-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageToVidConvert.setIcon(icon11)
        self.imageToVidConvert.setObjectName("imageToVidConvert")
        self.verticalLayout_34.addWidget(self.imageToVidConvert)
        self.verticalLayout_33.addWidget(self.frame_7)
        self.horizontalLayout_29.addWidget(self.frame_2)
        self.horizontalLayout_28.addWidget(self.imageToVidLabelFrame)
        self.stackedWidget.addWidget(self.imageToVid)
        self.sysInfoOverall = QtWidgets.QWidget()
        self.sysInfoOverall.setObjectName("sysInfoOverall")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.sysInfoOverall)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.testWidget = QtWidgets.QStackedWidget(self.sysInfoOverall)
        self.testWidget.setObjectName("testWidget")
        self.horizontalLayout_18.addWidget(self.testWidget)
        self.stackedWidget.addWidget(self.sysInfoOverall)
        self.settingsPreferences = QtWidgets.QWidget()
        self.settingsPreferences.setObjectName("settingsPreferences")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.settingsPreferences)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.settingsPreferences)
        self.label_13.setStyleSheet("font: 24pt \"Century Gothic\";\n"
"color: rgb(230, 230, 230);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_26.addWidget(self.label_13)
        self.stackedWidget.addWidget(self.settingsPreferences)
        self.settingsVersionInfo = QtWidgets.QWidget()
        self.settingsVersionInfo.setObjectName("settingsVersionInfo")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.settingsVersionInfo)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_12 = QtWidgets.QLabel(self.settingsVersionInfo)
        self.label_12.setStyleSheet("font: 24pt \"Century Gothic\";\n"
"color: rgb(230, 230, 230);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_25.addWidget(self.label_12)
        self.stackedWidget.addWidget(self.settingsVersionInfo)
        self.horizontalLayout_13.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.mainBodyContents)
        self.footerFrame = QtWidgets.QFrame(self.mainBody)
        self.footerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footerFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.footerVersionFrame = QtWidgets.QFrame(self.footerFrame)
        self.footerVersionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footerVersionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footerVersionFrame.setObjectName("footerVersionFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.footerVersionFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.versionLabel = QtWidgets.QLabel(self.footerVersionFrame)
        self.versionLabel.setStyleSheet("color: rgb(230, 230, 230);\n"
"font: 14pt \"Century Gothic\";")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout_7.addWidget(self.versionLabel)
        self.horizontalLayout_3.addWidget(self.footerVersionFrame)
        self.foorterDuckFrame = QtWidgets.QFrame(self.footerFrame)
        self.foorterDuckFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foorterDuckFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foorterDuckFrame.setObjectName("foorterDuckFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.foorterDuckFrame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.footerDuck = QtWidgets.QPushButton(self.foorterDuckFrame)
        self.footerDuck.setStyleSheet("border-style: flat;")
        self.footerDuck.setText("")
        self.footerDuck.setIcon(icon)
        self.footerDuck.setIconSize(QtCore.QSize(40, 40))
        self.footerDuck.setObjectName("footerDuck")
        self.horizontalLayout_6.addWidget(self.footerDuck)
        self.horizontalLayout_3.addWidget(self.foorterDuckFrame)
        self.sizeGrip = QtWidgets.QFrame(self.footerFrame)
        self.sizeGrip.setMinimumSize(QtCore.QSize(10, 10))
        self.sizeGrip.setMaximumSize(QtCore.QSize(10, 10))
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sizeGrip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_3.addWidget(self.sizeGrip, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footerFrame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.dropMenu.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sideMenuLabel.setText(_translate("MainWindow", "RPI Interface"))
        self.imageToVideo.setText(_translate("MainWindow", "Image to Video"))
        self.dropMenu.setItemText(self.dropMenu.indexOf(self.toolsPage), _translate("MainWindow", "Tools"))
        self.overall.setText(_translate("MainWindow", "Overall"))
        self.dropMenu.setItemText(self.dropMenu.indexOf(self.systemInformationPage), _translate("MainWindow", "System Information"))
        self.versionInformation.setText(_translate("MainWindow", "Version Information"))
        self.preferences.setText(_translate("MainWindow", "Preferences"))
        self.dropMenu.setItemText(self.dropMenu.indexOf(self.settingsPage), _translate("MainWindow", "Settings"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.label_14.setText(_translate("MainWindow", "Home"))
        self.imageToVidTitle.setText(_translate("MainWindow", "Image to .mp4 Converter"))
        self.imageToVidUploadFile.setText(_translate("MainWindow", "Upload File"))
        self.imageToVidUploadFolder.setText(_translate("MainWindow", "Upload Directory"))
        self.label_15.setText(_translate("MainWindow", "Double-Click Cell to Change Value"))
        self.imageToVidConvert.setText(_translate("MainWindow", "Convert to .mp4"))
        self.label_13.setText(_translate("MainWindow", "Settings Prefereces"))
        self.label_12.setText(_translate("MainWindow", "Settings Version Information"))
        self.versionLabel.setText(_translate("MainWindow", "RPi Interface v0.0.2022.1"))

import icons_rc
